
spring.datasource.url=jdbc:postgresql://localhost:5432/valorant_db

spring.datasource.username=valorant_user

spring.datasource.password=yourpassword

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080

riot.api.key=RGAPI-27326c11-498c-4d81-aff4-4a3722eff274


